@CalendarApp.Api_HostAddress = http://localhost:5196

GET {{CalendarApp.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{CalendarApp.Api_HostAddress}}/api/account/register
Content-Type: application/json

{
  "username": "Admin",
  "password": "Pa$$w0rd"
}

###

POST {{CalendarApp.Api_HostAddress}}/api/account/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "Pa$$w0rd"
}

###

POST {{CalendarApp.Api_HostAddress}}/api/subjects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMDc3Njk3NSwiZXhwIjoxNzExMzgxNzc1LCJpYXQiOjE3MTA3NzY5NzV9.oI3dqWchawwMDCG6iHf7UEp3SaHT0W2YvOKmXsY_LdOsp8tueOGihB2GkgK6N80mp15FIGYozKs7nRiEcHwHTA

{
  "name": "Kryptografia",
  "facultyType": 2
}

###

GET {{CalendarApp.Api_HostAddress}}/api/subjects
Content-Type: application/json

###

GET {{CalendarApp.Api_HostAddress}}/api/scheduled-classes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMzI4MDY0NiwiZXhwIjoxNzEzODg1NDQ2LCJpYXQiOjE3MTMyODA2NDZ9.BVPTQccZqerSiKfcyBOH72luv2pB2gTGOIkQ3NGq7cqZyKkwZun_F0w4W4-rrDhva3cxxLl5xtRudLJ0RDeYHA

###

POST {{CalendarApp.Api_HostAddress}}/api/scheduled-classes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMzI4MDY0NiwiZXhwIjoxNzEzODg1NDQ2LCJpYXQiOjE3MTMyODA2NDZ9.BVPTQccZqerSiKfcyBOH72luv2pB2gTGOIkQ3NGq7cqZyKkwZun_F0w4W4-rrDhva3cxxLl5xtRudLJ0RDeYHA

{
    "subjectId": 1,
    "startTime": "2021-01-01T00:00:00",
    "endTime": "2021-01-01T01:00:00"
}

###

PUT {{CalendarApp.Api_HostAddress}}/api/scheduled-classes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMzI4MDY0NiwiZXhwIjoxNzEzODg1NDQ2LCJpYXQiOjE3MTMyODA2NDZ9.BVPTQccZqerSiKfcyBOH72luv2pB2gTGOIkQ3NGq7cqZyKkwZun_F0w4W4-rrDhva3cxxLl5xtRudLJ0RDeYHA

{
  "subjectId": 1,
  "startTime": "2021-01-01T00:00:00",
  "endTime": "2021-01-01T01:00:00"
}

###

DELETE {{CalendarApp.Api_HostAddress}}/api/scheduled-classes/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMzI4MDY0NiwiZXhwIjoxNzEzODg1NDQ2LCJpYXQiOjE3MTMyODA2NDZ9.BVPTQccZqerSiKfcyBOH72luv2pB2gTGOIkQ3NGq7cqZyKkwZun_F0w4W4-rrDhva3cxxLl5xtRudLJ0RDeYHA

###

POST {{CalendarApp.Api_HostAddress}}/api/scheduled-classes/1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMzI4MDY0NiwiZXhwIjoxNzEzODg1NDQ2LCJpYXQiOjE3MTMyODA2NDZ9.BVPTQccZqerSiKfcyBOH72luv2pB2gTGOIkQ3NGq7cqZyKkwZun_F0w4W4-rrDhva3cxxLl5xtRudLJ0RDeYHA

{
  "title": "Test Note",
  "content": "Test Note"
}

###

GET {{CalendarApp.Api_HostAddress}}/api/scheduled-classes/1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMzI4MDY0NiwiZXhwIjoxNzEzODg1NDQ2LCJpYXQiOjE3MTMyODA2NDZ9.BVPTQccZqerSiKfcyBOH72luv2pB2gTGOIkQ3NGq7cqZyKkwZun_F0w4W4-rrDhva3cxxLl5xtRudLJ0RDeYHA


###

GET {{CalendarApp.Api_HostAddress}}/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlVzZXIiLCJuYW1laWQiOiIwIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDk3NTUzNzIsImV4cCI6MTcxMDM2MDE3MiwiaWF0IjoxNzA5NzU1MzcyfQ.OfC8XZF2kCkvA66m15LQCt9se2uGJLzCI0LHLyN1DEHvfIU9Tq6ACVWE15bkEgNGl6B3lYhqURgVRHExltwWZw


###


