@CalendarApp.Api_HostAddress = http://localhost:5196

GET {{CalendarApp.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{CalendarApp.Api_HostAddress}}/api/account/register
Content-Type: application/json

{
  "username": "Admin",
  "password": "Pa$$w0rd"
}

###

POST {{CalendarApp.Api_HostAddress}}/api/account/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "Pa$$w0rd"
}

###

POST {{CalendarApp.Api_HostAddress}}/api/subjects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiNyIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNDExNTkxMiwiZXhwIjoxNzE0NzIwNzEyLCJpYXQiOjE3MTQxMTU5MTJ9.bcQkPM6I94Ho6rMv69ltDwFql3tdhpfGx15Bnt0enZRfew4KZXMY3OlTAjp0kq7tzs0KERq2zK_DN5Anoh9g2g

{
  "name": "Kryptografia",
  "facultyType": 2
}

###

GET {{CalendarApp.Api_HostAddress}}/api/subjects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMzI4MDY0NiwiZXhwIjoxNzEzODg1NDQ2LCJpYXQiOjE3MTMyODA2NDZ9.BVPTQccZqerSiKfcyBOH72luv2pB2gTGOIkQ3NGq7cqZyKkwZun_F0w4W4-rrDhva3cxxLl5xtRudLJ0RDeYHA

###

GET {{CalendarApp.Api_HostAddress}}/api/scheduled-classes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNDExNzYxNCwiZXhwIjoxNzE0NzIyNDE0LCJpYXQiOjE3MTQxMTc2MTR9.CIOGlK4-pegf6CrVPFr-x_c_gKq1mZNAHozdXncS6QyqAJeQgCl4WqJfLToTp8gWHmcGhvHL8sENYNrKK8jFjQ


###

POST {{CalendarApp.Api_HostAddress}}/api/scheduled-classes
Content-Type: application/json

{
    "subjectId": 1,
    "startTime": "2021-01-01T00:00:00",
    "endTime": "2021-01-01T01:00:00"
}

###

PUT {{CalendarApp.Api_HostAddress}}/api/scheduled-classes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxMzI4MDY0NiwiZXhwIjoxNzEzODg1NDQ2LCJpYXQiOjE3MTMyODA2NDZ9.BVPTQccZqerSiKfcyBOH72luv2pB2gTGOIkQ3NGq7cqZyKkwZun_F0w4W4-rrDhva3cxxLl5xtRudLJ0RDeYHA

{
  "subjectId": 1,
  "startTime": "2021-01-01T00:00:00",
  "endTime": "2021-01-01T01:00:00"
}

###

DELETE {{CalendarApp.Api_HostAddress}}/api/scheduled-classes/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNDA0MjkzNCwiZXhwIjoxNzE0NjQ3NzM0LCJpYXQiOjE3MTQwNDI5MzR9.g_Oz9LpAcMjtIS05v_OlGMmXU7YXVKH0T1HuHgnuu-K7MaRGlfpjigT0UltSPAwoIPb4VqLIv9NLmpItQH5NSw

###

POST {{CalendarApp.Api_HostAddress}}/api/scheduled-classes/1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNDExNzYxNCwiZXhwIjoxNzE0NzIyNDE0LCJpYXQiOjE3MTQxMTc2MTR9.CIOGlK4-pegf6CrVPFr-x_c_gKq1mZNAHozdXncS6QyqAJeQgCl4WqJfLToTp8gWHmcGhvHL8sENYNrKK8jFjQ

{
  "title": "Test Note",
  "content": "Test Note"
}

###

GET {{CalendarApp.Api_HostAddress}}/api/scheduled-classes/1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNDExNzYxNCwiZXhwIjoxNzE0NzIyNDE0LCJpYXQiOjE3MTQxMTc2MTR9.CIOGlK4-pegf6CrVPFr-x_c_gKq1mZNAHozdXncS6QyqAJeQgCl4WqJfLToTp8gWHmcGhvHL8sENYNrKK8jFjQ


###

GET {{CalendarApp.Api_HostAddress}}/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlVzZXIiLCJuYW1laWQiOiIwIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDk3NTUzNzIsImV4cCI6MTcxMDM2MDE3MiwiaWF0IjoxNzA5NzU1MzcyfQ.OfC8XZF2kCkvA66m15LQCt9se2uGJLzCI0LHLyN1DEHvfIU9Tq6ACVWE15bkEgNGl6B3lYhqURgVRHExltwWZw


###

###

###

POST {{CalendarApp.Api_HostAddress}}/api/tests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiNyIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNDExNTkxMiwiZXhwIjoxNzE0NzIwNzEyLCJpYXQiOjE3MTQxMTU5MTJ9.bcQkPM6I94Ho6rMv69ltDwFql3tdhpfGx15Bnt0enZRfew4KZXMY3OlTAjp0kq7tzs0KERq2zK_DN5Anoh9g2g

{
  "subjectId": 4,
  "title": "Test1",
  "startTime": "2021-03-03"
}

###

PUT {{CalendarApp.Api_HostAddress}}/api/tests/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiNyIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNDExNTkxMiwiZXhwIjoxNzE0NzIwNzEyLCJpYXQiOjE3MTQxMTU5MTJ9.bcQkPM6I94Ho6rMv69ltDwFql3tdhpfGx15Bnt0enZRfew4KZXMY3OlTAjp0kq7tzs0KERq2zK_DN5Anoh9g2g

{
  "title": "Test2",
  "startTime": "2021-03-03"
}
###

DELETE {{CalendarApp.Api_HostAddress}}/api/tests/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwibmFtZWlkIjoiNyIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNDExNTkxMiwiZXhwIjoxNzE0NzIwNzEyLCJpYXQiOjE3MTQxMTU5MTJ9.bcQkPM6I94Ho6rMv69ltDwFql3tdhpfGx15Bnt0enZRfew4KZXMY3OlTAjp0kq7tzs0KERq2zK_DN5Anoh9g2g
